// Compile spec/tools/*.json into lib/src/builtin/defs.g.dart.
//
// The bundled capability definitions are data, shared byte for byte with
// the Python package this is a port of. Dart has no portable way to read a
// package's own data files at runtime, so they are embedded as string
// constants instead — generated, never edited.
//
//     dart run tool/generate_defs.dart
//
// CI runs this and fails if the committed output differs.
import 'dart:convert';
import 'dart:io';

void main() {
  final dir = Directory('spec/tools');
  final files = dir.listSync().whereType<File>().where((f) => f.path.endsWith('.json')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_defs.dart — do not edit.')
    ..writeln('// Source: spec/tools/*.json, shared with the Python package.')
    ..writeln('library;')
    ..writeln()
    ..writeln('import \'dart:convert\';')
    ..writeln()
    ..writeln('const Map<String, String> _raw = {');
  for (final file in files) {
    final name = file.uri.pathSegments.last.replaceAll('.json', '');
    // Re-encode rather than copying the file text: this pins the bytes to
    // the parsed value, so formatting in the JSON file cannot change what
    // the package loads.
    final encoded = jsonEncode(jsonDecode(file.readAsStringSync()));
    buf.writeln("  '$name': r'''$encoded''',");
  }
  buf
    ..writeln('};')
    ..writeln()
    ..writeln('/// Return a fresh copy of the named definition set.')
    ..writeln('Object? load(String name) => jsonDecode(_raw[name]!);');

  File('lib/src/builtin/defs.g.dart').writeAsStringSync(buf.toString());
  stdout.writeln('wrote lib/src/builtin/defs.g.dart from ${files.length} files');
}
